// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "user_name", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "nick_name", Type: field.TypeString, Size: 128},
		{Name: "real_name", Type: field.TypeString, Size: 128},
		{Name: "email", Type: field.TypeString, Size: 127},
		{Name: "phone", Type: field.TypeString, Size: 11},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_id",
				Unique:  true,
				Columns: []*schema.Column{UserColumns[0]},
			},
			{
				Name:    "user_id_user_name",
				Unique:  true,
				Columns: []*schema.Column{UserColumns[0], UserColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
	}
)

func init() {
	UserTable.Annotation = &entsql.Annotation{
		Table:     "user",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
}
