registry:
  type: "consul"

  consul:
    address: "localhost:8500"
    scheme: "http"
    heartbeat: false
    health_check: false
    health_check_interval: 5

  etcd:
    endpoints:
      - "localhost:8500"

  zookeeper:
    endpoints:
      - "localhost:8500"
    timeout: 10s

  kubernetes:
    namespace: "go-micro"
